extends:
  - stylelint-config-standard-scss
  - stylelint-config-prettier-scss
rules:
  scss/at-import-no-partial-leading-underscore: null
  scss/load-no-partial-leading-underscore: null
  selector-class-pattern: null
  scss/dollar-variable-pattern: null
  scss/at-mixin-pattern:
    - ^[a-z][a-z0-9]*(-[a-z0-9]+)*$
    - message: Имена миксинов должны быть в kebab-case (например, my-mixin)
  selector-pseudo-element-colon-notation: 'single'
  scss/dollar-variable-empty-line-before: null
  block-no-empty: null
  declaration-empty-line-before: null
  color-function-notation: null
  alpha-value-notation: null
  no-descending-specificity: null
  scss/double-slash-comment-empty-line-before: null
  declaration-block-no-redundant-longhand-properties: null
  shorthand-property-no-redundant-values: null
  color-hex-length: null
  no-empty-source: null
